%% Bytes to escape
-define(FRAME_DELIMITER, 16#7E).
-define(ESCAPE, 16#7D).
-define(XON, 16#11).
-define(XOFF, 16#13).

%% API frame names and values
-define(AT_FRAME, 16#08).
-define(QUEUE_PARAM_VALUE_FRAME, 16#09).
-define(ZB_TRANSMIT_REQUEST_FRAME, 16#10).
-define(ZB_EXPLICIT_COMMAND_FRAME, 16#11).
-define(AT_REMOTE_REQUEST_FRAME, 16#17).
-define(CREATE_SOURCE_RT_FRAME, 16#21).
-define(AT_RESPONSE_FRAME, 16#88).
-define(MODEM_STATUS_FRAME, 16#8A).
-define(ZB_TRANSMIT_STATUS_FRAME, 16#8B).
-define(ZB_RECEIVE_PACKET_FRAME, 16#90).
-define(ZB_EXPL_RX_INDICATOR_FRAME, 16#91).
-define(ZB_IO_DATA_RX_INDICATOR_FRAME, 16#92).
-define(XB_SENSOR_READ_FRAME, 16#94).
-define(NODE_ID_FRAME, 16#95).
-define(AT_REMOTE_RESPONSE_FRAME, 16#97).
-define(OTA_FIRMWARE_UPDATE_STATUS_FRAME, 16#A0).
-define(ROUTE_RECORD_INDICATOR_FRAME, 16#A1).
-define(M21_ROUTE_REQUEST_INDICATOR_FRAME, 16#A3).

